"""Agent enrollment ("runtime pairing").

WHY THIS EXISTS
---------------
Manual registration asks a normal user to generate an Ed25519 keypair and paste
the public key into the dashboard. Pairing removes that step WITHOUT moving the
private key anywhere:

    Dashboard (owner session)          Agent Runtime (owner's machine)
    -------------------------          -------------------------------
    1. create enrollment  ───────────► code shown once, 15 min TTL
                                       2. `agent_runtime enroll <code>`
                                          generates key LOCALLY
                                          signs PoP payload
                                       ◄── 3. claim(code, public_key, PoP)
    4. owner sees key fingerprint,
       compares with the runtime's,
       signs the EXISTING owner
       challenge (op=register)
    5. complete  ─────────────────────► agent_id + key_id created
                                       6. runtime polls status(code),
                                          stores agent_id/key_id (public)

INVARIANTS
----------
* The private key is generated by the runtime and never leaves it. AEra only
  receives the public key plus a signature proving the sender holds the key.
* The enrollment secret is stored only as SHA-256; comparisons are
  constant-time. It is never logged or echoed back.
* Only the owner who created the enrollment can complete it, and only with a
  valid owner-wallet signature over an owner challenge bound to THIS enrollment
  (`agent_id = "enrollment:<id>"`). Such a challenge can never be consumed by
  `/register` (which requires agent_id NULL), nor can a /register challenge
  complete an enrollment.
* An enrollment is single-claim and single-completion; state transitions are
  guarded with conditional UPDATEs inside `BEGIN IMMEDIATE`.
* The resulting agent is created by the SAME function as `/register`, so the
  identity is indistinguishable from a manually registered one.
"""
from __future__ import annotations

import hashlib
import hmac
import re
import secrets
from datetime import datetime, timedelta, timezone
from typing import Any, Optional

from . import audit, capabilities as cap_mod, repository
from .constants import (
    AGENT_ENROLL_KEYS,
    ENROLLMENT_CHALLENGE_PREFIX,
    ENROLLMENT_TTL_SECONDS,
    MAX_OPEN_ENROLLMENTS_PER_OWNER,
    OWNER_DOMAIN,
    PROTO_AGENT_ENROLL,
    PROTOCOL_VERSION,
)
from .crypto import canonical_json, decode_public_key, public_key_fingerprint, verify_signature

CODE_PREFIX = "aera-enroll-"
_EID_RE = re.compile(r"^[0-9a-f]{16}$")
_CODE_RE = re.compile(r"^aera-enroll-([0-9a-f]{16})\.([A-Za-z0-9_-]{32})$")

STATUS_PENDING = "pending"
STATUS_KEY_SUBMITTED = "key_submitted"
STATUS_COMPLETED = "completed"
STATUS_CANCELLED = "cancelled"
OPEN_STATUSES = (STATUS_PENDING, STATUS_KEY_SUBMITTED)

MAX_LABEL_LEN = 80


class EnrollmentError(Exception):
    def __init__(self, code: str, http_status: int = 400) -> None:
        super().__init__(code)
        self.code = code
        self.http_status = http_status


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def _hash_secret(secret: str) -> str:
    return hashlib.sha256(secret.encode("ascii")).hexdigest()


def parse_code(code: Any) -> tuple[str, str]:
    """Split `aera-enroll-<eid>.<secret>`. Raises on anything else."""
    if not isinstance(code, str):
        raise EnrollmentError("invalid_enrollment_code", 400)
    m = _CODE_RE.match(code.strip())
    if not m:
        raise EnrollmentError("invalid_enrollment_code", 400)
    return m.group(1), m.group(2)


def is_valid_enrollment_id(eid: str) -> bool:
    return bool(isinstance(eid, str) and _EID_RE.match(eid))


def challenge_binding(enrollment_id: str) -> str:
    """The owner-challenge `agent_id` that binds a signature to one enrollment."""
    return ENROLLMENT_CHALLENGE_PREFIX + enrollment_id


def build_pop_payload(enrollment_id: str, public_key: str) -> bytes:
    """Bytes the runtime signs with the NEW private key (proof of possession)."""
    return canonical_json({
        "protocol": PROTO_AGENT_ENROLL,
        "version": PROTOCOL_VERSION,
        "enrollment_id": enrollment_id,
        "public_key": public_key,
        "domain": OWNER_DOMAIN,
    }, AGENT_ENROLL_KEYS)


def _now() -> str:
    return repository.utcnow_iso()


def _expired(row) -> bool:
    return row["expires_at"] <= _now()


def _row_by_code(conn, code: str):
    eid, secret = parse_code(code)
    row = conn.execute("SELECT * FROM agent_enrollments WHERE enrollment_id=?",
                       (eid,)).fetchone()
    # Same error for unknown id and wrong secret: no enrollment-id oracle.
    if row is None or not hmac.compare_digest(row["secret_hash"], _hash_secret(secret)):
        raise EnrollmentError("invalid_enrollment_code", 404)
    return row


def _public_view(row) -> dict[str, Any]:
    """Owner-facing view. Never contains the secret or its hash."""
    status = row["status"]
    if status in OPEN_STATUSES and _expired(row):
        status = "expired"
    out: dict[str, Any] = {
        "enrollment_id": row["enrollment_id"],
        "status": status,
        "label": row["label"],
        "capabilities": repository.loads_capabilities(row["capabilities"]),
        "created_at": row["created_at"],
        "expires_at": row["expires_at"],
        "key_fingerprint": None,
        "agent_id": row["agent_id"],
        "key_id": row["key_id"],
    }
    if row["public_key"]:
        out["key_fingerprint"] = public_key_fingerprint(row["public_key"])
    return out


# --------------------------------------------------------------------------- #
# 1. create (owner, authenticated by the dashboard session)
# --------------------------------------------------------------------------- #
def create(*, owner_wallet: str, label: Optional[str],
           capabilities: Optional[list[str]]) -> dict[str, Any]:
    owner = (owner_wallet or "").lower()
    if not owner:
        raise EnrollmentError("unauthorized", 401)
    label = (label or "").strip()
    if len(label) < 3 or len(label) > MAX_LABEL_LEN:
        raise EnrollmentError("invalid_label", 400)
    caps = cap_mod.normalize(capabilities)

    eid = secrets.token_hex(8)
    secret = secrets.token_urlsafe(24)          # 32 chars, 192 bits
    now = _now()
    expires = (datetime.now(timezone.utc) + timedelta(seconds=ENROLLMENT_TTL_SECONDS)
               ).strftime("%Y-%m-%dT%H:%M:%SZ")

    with repository.transaction() as conn:
        open_count = conn.execute(
            "SELECT COUNT(*) FROM agent_enrollments WHERE owner_wallet=? "
            "AND status IN (?, ?) AND expires_at > ?",
            (owner, STATUS_PENDING, STATUS_KEY_SUBMITTED, now),
        ).fetchone()[0]
        if open_count >= MAX_OPEN_ENROLLMENTS_PER_OWNER:
            raise EnrollmentError("too_many_open_enrollments", 429)
        conn.execute(
            "INSERT INTO agent_enrollments(enrollment_id, owner_wallet, secret_hash, label, "
            "capabilities, status, created_at, expires_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (eid, owner, _hash_secret(secret), label,
             repository.dumps_capabilities(caps), STATUS_PENDING, now, expires),
        )
        audit.log_event("agent.enrollment_created", actor="owner",
                        meta={"owner_wallet": owner, "enrollment_id": eid}, conn=conn)

    return {
        "enrollment_id": eid,
        # Returned exactly once. Only its hash is stored.
        "enrollment_code": f"{CODE_PREFIX}{eid}.{secret}",
        "expires_at": expires,
        "label": label,
        "capabilities": caps,
    }


# --------------------------------------------------------------------------- #
# 2. claim (runtime, authenticated by the enrollment secret + PoP)
# --------------------------------------------------------------------------- #
def claim(*, code: str, public_key: str, signature: str) -> dict[str, Any]:
    try:
        decode_public_key(public_key)
    except ValueError:
        raise EnrollmentError("invalid_public_key", 400)

    with repository.transaction() as conn:
        row = _row_by_code(conn, code)
        if _expired(row):
            raise EnrollmentError("enrollment_expired", 410)
        if row["status"] != STATUS_PENDING:
            raise EnrollmentError("enrollment_already_claimed", 409)
        if not verify_signature(public_key, signature,
                                build_pop_payload(row["enrollment_id"], public_key)):
            raise EnrollmentError("invalid_proof_of_possession", 401)
        # A key already bound to an active identity must not be enrolled again:
        # one key, one agent.
        dup = conn.execute(
            "SELECT 1 FROM agent_keys WHERE public_key=? AND status='active'",
            (public_key,),
        ).fetchone()
        if dup is not None:
            raise EnrollmentError("key_already_registered", 409)
        cur = conn.execute(
            "UPDATE agent_enrollments SET status=?, public_key=?, claimed_at=? "
            "WHERE enrollment_id=? AND status=?",
            (STATUS_KEY_SUBMITTED, public_key, _now(), row["enrollment_id"], STATUS_PENDING),
        )
        if cur.rowcount != 1:
            raise EnrollmentError("enrollment_already_claimed", 409)
        audit.log_event("agent.enrollment_claimed", actor="runtime",
                        meta={"enrollment_id": row["enrollment_id"]}, conn=conn)
        eid = row["enrollment_id"]

    return {"enrollment_id": eid, "status": STATUS_KEY_SUBMITTED,
            "key_fingerprint": public_key_fingerprint(public_key)}


# --------------------------------------------------------------------------- #
# 3. runtime status poll (authenticated by the enrollment secret)
# --------------------------------------------------------------------------- #
def runtime_status(*, code: str) -> dict[str, Any]:
    conn = repository.get_connection()
    try:
        row = _row_by_code(conn, code)
    finally:
        conn.close()
    view = _public_view(row)
    # agent_id / key_id are public identifiers; exposing them to the holder of
    # the code is the whole point of the poll.
    return {"enrollment_id": view["enrollment_id"], "status": view["status"],
            "agent_id": view["agent_id"], "key_id": view["key_id"],
            "key_fingerprint": view["key_fingerprint"]}


# --------------------------------------------------------------------------- #
# 4. owner view / cancel (dashboard session)
# --------------------------------------------------------------------------- #
def _owned_row(conn, owner: str, eid: str):
    if not is_valid_enrollment_id(eid):
        raise EnrollmentError("unknown_enrollment", 404)
    row = conn.execute("SELECT * FROM agent_enrollments WHERE enrollment_id=?",
                       (eid,)).fetchone()
    # Same 404 for missing and foreign: no enumeration of other owners.
    if row is None or row["owner_wallet"] != (owner or "").lower():
        raise EnrollmentError("unknown_enrollment", 404)
    return row


def owner_view(*, owner_wallet: str, enrollment_id: str) -> dict[str, Any]:
    conn = repository.get_connection()
    try:
        return _public_view(_owned_row(conn, owner_wallet, enrollment_id))
    finally:
        conn.close()


def cancel(*, owner_wallet: str, enrollment_id: str) -> dict[str, Any]:
    with repository.transaction() as conn:
        row = _owned_row(conn, owner_wallet, enrollment_id)
        if row["status"] not in OPEN_STATUSES:
            raise EnrollmentError("enrollment_not_open", 409)
        conn.execute("UPDATE agent_enrollments SET status=? WHERE enrollment_id=?",
                     (STATUS_CANCELLED, enrollment_id))
        audit.log_event("agent.enrollment_cancelled", actor="owner",
                        meta={"enrollment_id": enrollment_id}, conn=conn)
    return {"enrollment_id": enrollment_id, "status": STATUS_CANCELLED}


# --------------------------------------------------------------------------- #
# 5. complete (owner wallet signature) — called from routes.py
# --------------------------------------------------------------------------- #
def complete(conn, *, enrollment_id: str, owner_wallet: str, create_agent) -> dict[str, Any]:
    """Create the agent from a claimed enrollment.

    The caller MUST already have consumed an owner challenge with
    operation=register and agent_id=challenge_binding(enrollment_id) for
    `owner_wallet`, inside the same transaction `conn`.
    """
    row = _owned_row(conn, owner_wallet, enrollment_id)
    if _expired(row):
        raise EnrollmentError("enrollment_expired", 410)
    if row["status"] == STATUS_PENDING:
        raise EnrollmentError("enrollment_not_claimed", 409)
    if row["status"] != STATUS_KEY_SUBMITTED:
        raise EnrollmentError("enrollment_not_open", 409)

    caps = repository.loads_capabilities(row["capabilities"])
    agent_id, key_id = create_agent(conn, owner_wallet=row["owner_wallet"],
                                    public_key=row["public_key"], label=row["label"],
                                    caps=caps, via="enrollment")
    cur = conn.execute(
        "UPDATE agent_enrollments SET status=?, agent_id=?, key_id=?, completed_at=? "
        "WHERE enrollment_id=? AND status=?",
        (STATUS_COMPLETED, agent_id, key_id, _now(), enrollment_id, STATUS_KEY_SUBMITTED),
    )
    if cur.rowcount != 1:
        raise EnrollmentError("enrollment_not_open", 409)
    return {"agent_id": agent_id, "key_id": key_id, "capabilities": caps}
