"""Pydantic models for the Agent Identity API."""
from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class OwnerChallengeRequest(BaseModel):
    owner_wallet: str
    operation: str
    agent_id: Optional[str] = None


class OwnerChallengeResponse(BaseModel):
    challenge_id: str
    challenge: str
    expires_at: str
    domain: str
    protocol: str
    version: str
    owner_wallet: str
    agent_id: str
    operation: str


class RegisterRequest(BaseModel):
    owner_wallet: str
    owner_challenge_id: str
    owner_signature: str
    public_key: str  # ed25519:<b64u>
    label: Optional[str] = None
    capabilities: Optional[list[str]] = None


class RegisterResponse(BaseModel):
    agent_id: str
    key_id: str
    capabilities: list[str]


class AddKeyRequest(BaseModel):
    owner_wallet: str
    owner_challenge_id: str
    owner_signature: str
    public_key: str


class RotateKeyRequest(BaseModel):
    owner_wallet: str
    owner_challenge_id: str
    owner_signature: str
    new_public_key: str
    revoke_key_id: str


class AgentChallengeRequest(BaseModel):
    key_id: str
    aud: str


class AuthenticateRequest(BaseModel):
    challenge_id: str
    key_id: str
    aud: str
    signature: str  # base64url ed25519(64B)


class TokenRevokeRequest(BaseModel):
    jti: str


class MessageRequest(BaseModel):
    payload: dict
    signature: str
    content: Optional[str] = None  # optional relayed opaque content


class InteractionRequest(BaseModel):
    payload: dict
    signature: str
    interaction_type: int
    responder_agent_id: Optional[str] = None
    metadata: Optional[dict] = None


class CapabilitiesPatchRequest(BaseModel):
    owner_wallet: str
    owner_challenge_id: str
    owner_signature: str
    capabilities: list[str]


# --- Enrollment / runtime pairing -------------------------------------------
class EnrollmentClaimRequest(BaseModel):
    enrollment_code: str
    public_key: str      # ed25519:<b64u>, generated by the runtime
    signature: str       # b64u Ed25519 over the enroll PoP payload


class EnrollmentStatusRequest(BaseModel):
    enrollment_code: str


class EnrollmentCompleteRequest(BaseModel):
    owner_wallet: str
    owner_challenge_id: str
    owner_signature: str
